# Challenge Headmaster
[[npc]]
inherit=379
name="Challenge Headmaster"
op1="Talk-to"
op3="View Challenges"

# Challenge Headmaster
[[npc]]
inherit=3307
name="Pk Master"
op1="Talk-to"
op2="Buy"
op3="Sell"
op4="Set Pk Master Account"

# Grand Exchange Clerk
[[npc]]
inherit=2148
op2="Exchange"
op3="History"
op4="Offers Viewer"
op5="Sets"

# Grand Exchange Clerk
[[npc]]
inherit=2149
op2="Exchange"
op3="History"
op4="Offers Viewer"
op5="Sets"

# Grand Exchange Clerk
[[npc]]
inherit=2150
op2="Exchange"
op3="History"
op4="Offers Viewer"
op5="Sets"

# Grand Exchange Clerk
[[npc]]
inherit=2151
op2="Exchange"
op3="History"
op4="Offers Viewer"
op5="Sets"

# Zenyte guide
[[npc]]
inherit=3308
name="%SERVER_NAME% guide"
op2="Trade"

# Zahur
[[npc]]
inherit=4753
op2="Decant"
op3="Clean"
op4="Crush secondaries"
op5="Make unfinished potion(s)"

# Perdu
[[npc]]
inherit=7456
op1="Repair"
op3=""

# Zenyte Teleporter
[[npc]]
id=10000
inherit=4398
name="%SERVER_NAME% Teleporter"
op1="Teleport"
op4="Teleport-previous"
models=[28220, 214, 250, 28991, 28226, 28224, 177, 534, 10698, 28223, 29249]
standanimation=813
walkanimation=1205
rotate90animation=1207
rotate180animation=1206
rotate270animation=1208

# Cynthia (Melee Armoury Shop)
[[npc]]
id=10001
inherit=1176
name="Cynthia"
ops=["", "", "Trade", "", ""]

# Arnas (Melee Weaponry Shop)
[[npc]]
id=10002
inherit=4105
name="Arnas"
ops=["", "", "Trade", "", ""]
models=[230, 246, 302, 168, 179, 263, 185, 491]

# Robin (Ranged Armoury Shop)
[[npc]]
id=10003
inherit=6067
name="Robin Hood"
combatlevel=0
ops=["", "", "Trade", "", ""]

# Fae (Ranged Weaponry Shop)
[[npc]]
id=10004
inherit=1157
name="Fae"
combatlevel=0
ops=["", "", "Trade", "", ""]
models=[390, 414, 477, 20429, 332, 356, 512, 422]

# Dhalius (Magic Weaponry Shop)
[[npc]]
id=10005
inherit=881
name="Dhalius"
ops=["", "", "Trade", "", ""]

# Hezaff (Magic Armoury Shop)
[[npc]]
id=10006
inherit=3232
name="Hezaff"
ops=["", "", "Trade", "Buy-teletabs", ""]

# John (Food Shop)
[[npc]]
id=10007
inherit=1027
name="John"
ops=["", "", "Trade", "", ""]
models=[18191, 217, 302, 3190, 10980, 176, 562, 254, 185, 246]

# Jackie (Skilling Shop)
[[npc]]
id=10008
inherit=5036
name="Jackie"
ops=["", "", "Trade", "Jewellery", ""]

# Frank (Vote Shop)
[[npc]]
id=10009
inherit=4225
name="Frank"
op1="Donation shop"
op3="Vote shop"
op4="Pharaoh shop"
op5="Event shop"

# Mac
[[npc]]
id=10010
inherit=6481
name="Mac"
combatlevel=0
op1="Talk-to"
op3="Trade"

# Combat dummy
[[npc]]
id=10019
inherit=2668
ops=["", "", "Attack", "", ""]
filteredops=["", "", "Attack", "", ""]

# Undead combat dummy
[[npc]]
id=10020
inherit=7413
ops=["", "", "Attack", "", ""]
filteredops=["", "", "Attack", "", ""]

# Make-over-mage
[[npc]]
id=10021
inherit=1307
op1="Talk-to"
op4="Makeover"
op5="Skin Colour"

# Zenyte Portal
[[object]]
id=35000
inherit=15478
name="%SERVER_NAME% Portal"
ops=["Teleport", "Teleport-previous", "", "", ""]


# Mounted Max Cape
[[object]]
id=35002
inherit=29170
op1=""
op2=""
op4=""
sizex=1
sizey=1

# Fairy ring
[[object]]
id=35003
inherit=29422
op4="Ring-last-destination"
op5=""
modelsizex=192
modelsizey=192
modelheight=192
sizex=3
sizey=3

# Grand Exchange Booth
[[object]]
inherit=10060
op1="Bank"
op2="Collect"
op3="Offers Viewer"
op4="Presets"

# Grand Exchange Booth
[[object]]
inherit=10061
op1=""
op2="Exchange"
op3="Collect"
op4="Offers Viewer"

# Saradomin Altar
[[object]]
inherit=18258
name="Saradomin altar"
op2="Regular"
op3="Ancient"
op4="Lunar"
op5="Arceuus"

# burn pit
[[object]]
inherit=33322
name="Burn Pit"
op1="Burn Items"


# upgrade rack
[[object]]
inherit=33020
name="Upgrade Rack"
op1="Upgrade Items"


# Wilderness Statistics
[[object]]
inherit=26756
op1="Toggle K/D"
op2=""

# Home lectern
[[object]]
id=35008
inherit=12136
name="Lectern"
op1="Study"
optionsinvisible=-1
accessblockflag=14

# Door
[[object]]
id=35009
inherit=11784
name="Door"
op1="Open"
optionsinvisible=-1

# Door
[[object]]
id=35010
inherit=11785
name="Door"
op1="Open"
optionsinvisible=-1

# Door
[[object]]
id=35011
inherit=11784
name="Door"
op1="Close"
optionsinvisible=-1

# Door
[[object]]
id=35012
inherit=11785
name="Door"
op1="Close"
optionsinvisible=-1

# Zenyte Home Teleport (Teletab)
[[item]]
id=22721
inherit=8007
name="Pharaoh home teleport"
grandexchange=true
invmodel=50000
placeholderid=30028
placeholdertemplate=-1
op2=""
op3=""
op4=""

# Zenyte Home Teleport (Teletab) (placeholder)
[[item]]
id=30028
inherit=15430
name="null"
placeholdertemplate=14401
placeholderid=22721
invmodel=50000

[item.parameters]
601="%SERVER_NAME% Home Teleport"

# Zenyte Home Teleport for spellbooks
[[item]]
inherit=[9712, 11142, 11143, 21835]

[item.parameters]
601="%SERVER_NAME% Home Teleport"

# Box of Restoration - base
[[object]]
id=29241
inherit=29241
name="Box of Restoration"
models=[]
offsety=20
varbit=16000
transformedids=[29241, 29241, -1]
sizex=2

# Box of Restoration - basic
[[object]]
id=29241
inherit=23709
name="Box of Restoration"
op1="Restore"
modelsizex=205
modelsizey=152
modelheight=190
offsety=20
sizex=2

# Box of Restoration - full
[[object]]
id=35022
inherit=23709
name="Box of Restoration"
op1="Restore"
op2="Remove-skull"
modelsizex=205
modelsizey=152
modelheight=190
offsety=20
sizex=2

# Box of Restoration varbit
[[varbit]]
id=16000
basevar=3800
startbit=0
endbit=1

# Daily Board
[[object]]
inherit=26756
name="Daily board"
id=35023
op1="Read"
op2=""

# Magic storage unit base
[[object]]
inherit=18803
name="Magic storage unit"
models=[]
varbit=16001
id=35024
transformedids=[35025, 35026, 818, -1]

# Magic storage unit locked
[[object]]
inherit=18802
name="Magic storage unit"
id=35025
op1="Unlock"
op2=""
op5=""

# Magic storage unit unlocked
[[object]]
inherit=18803
name="Magic storage unit"
id=35026
op1="Search"
op2=""

# Magic storage unit varbit
[[varbit]]
id=16001
basevar=3800
startbit=2
endbit=4

# Banker
[[npc]]
inherit=2117
id=10029
op1="Talk-to"
op2="Bank"
op3="Collect"
op4="Presets"

# Banker
[[npc]]
inherit=2118
id=10030
op1="Talk-to"
op2="Bank"
op3="Collect"
op4="Presets"