# Crystal crown original
[[item]]
id=23911
inherit=8959
name="Crystal crown"
placeholderid=23912
invmodel=50627
primarymalemodel=50628
primaryfemalemodel=50629
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown original Placeholder
[[item]]
id=23912
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23911
invmodel=50627
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown white
[[item]]
id=23913
inherit=8959
name="Crystal crown"
placeholderid=23914
invmodel=50630
primarymalemodel=50631
primaryfemalemodel=50632
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown white Placeholder
[[item]]
id=23914
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23913
invmodel=50630
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown black
[[item]]
id=23915
inherit=8959
name="Crystal crown"
placeholderid=23916
invmodel=50633
primarymalemodel=50634
primaryfemalemodel=50635
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown black Placeholder
[[item]]
id=23916
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23915
invmodel=50630
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown blue
[[item]]
id=23917
inherit=8959
name="Crystal crown"
placeholderid=23918
invmodel=50636
primarymalemodel=50637
primaryfemalemodel=50638
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown blue Placeholder
[[item]]
id=23918
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23917
invmodel=50636
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown red
[[item]]
id=23919
inherit=8959
name="Crystal crown"
placeholderid=23920
invmodel=50639
primarymalemodel=50640
primaryfemalemodel=50641
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown red Placeholder
[[item]]
id=23920
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23919
invmodel=50639
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown green
[[item]]
id=23921
inherit=8959
name="Crystal crown"
placeholderid=23922
invmodel=50642
primarymalemodel=50643
primaryfemalemodel=50644
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown green Placeholder
[[item]]
id=23922
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23921
invmodel=50642
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown dark green
[[item]]
id=23923
inherit=8959
name="Crystal crown"
placeholderid=23924
invmodel=50645
primarymalemodel=50646
primaryfemalemodel=50647
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown dark green Placeholder
[[item]]
id=23924
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23923
invmodel=50645
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown zenyte
[[item]]
id=23925
inherit=8959
name="Crystal crown"
placeholderid=23926
invmodel=50648
primarymalemodel=50649
primaryfemalemodel=50650
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown zenyte Placeholder
[[item]]
id=23926
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=23925
invmodel=50648
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown purple
[[item]]
id=32180
inherit=8959
name="Crystal crown"
placeholderid=32181
invmodel=50651
primarymalemodel=50652
primaryfemalemodel=50653
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown purple Placeholder
[[item]]
id=32181
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=32180
invmodel=50651
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3

# Crystal crown yellow
[[item]]
id=32182
inherit=8959
name="Crystal crown"
placeholderid=32183
invmodel=50654
primarymalemodel=50655
primaryfemalemodel=50656
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
grandexchange=false
notedid=-1
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3
price=30000000

# Crystal crown yellow Placeholder
[[item]]
id=32183
inherit=21020
name="null"
placeholdertemplate=14401
placeholderid=32182
invmodel=50654
zoom=912
modelroll=207
modelpitch=111
modelyaw=0
offsetx=-8
offsety=3