# Crystal of Ithell (white)
[[item]]
id=23927
inherit=1767
invmodel=50615
placeholderid=23928
name="Crystal of Ithell"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Ithell (white) (placeholder)
[[item]]
id=23928
inherit=1767
invmodel=50615
name="null"
placeholderid=23927
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Iorwerth (black)
[[item]]
id=23929
inherit=1767
invmodel=50616
placeholderid=23930
name="Crystal of Iorwerth"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Iorwerth (black) (placeholder)
[[item]]
id=23930
inherit=1767
invmodel=50616
name="null"
placeholderid=23929
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Trahaearn (purple)
[[item]]
id=23931
inherit=1767
invmodel=50617
placeholderid=23932
name="Crystal of Trahaearn"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Trahaearn (purple) (placeholder)
[[item]]
id=23932
inherit=1767
invmodel=50617
name="null"
placeholderid=23931
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Cadarn (green)
[[item]]
id=23933
inherit=1767
invmodel=50614
placeholderid=23934
name="Crystal of Cadarn"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Cadarn (green) (placeholder)
[[item]]
id=23934
inherit=1767
invmodel=50614
name="null"
placeholderid=23933
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Crwys (yellow)
[[item]]
id=23935
inherit=1767
invmodel=50618
placeholderid=23936
name="Crystal of Crwys"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Crwys (yellow) (placeholder)
[[item]]
id=23936
inherit=1767
invmodel=50618
name="null"
placeholderid=23935
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Meilyr (original)
[[item]]
id=23937
inherit=1767
invmodel=50619
placeholderid=23938
name="Crystal of Meilyr"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Meilyr (original) (placeholder)
[[item]]
id=23938
inherit=1767
invmodel=50619
name="null"
placeholderid=23937
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Hefin (red)
[[item]]
id=23939
inherit=1767
invmodel=50620
placeholderid=23940
name="Crystal of Hefin"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Hefin (red) (placeholder)
[[item]]
id=23940
inherit=1767
invmodel=50620
name="null"
placeholderid=23939
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Amlodd (blue)
[[item]]
id=23941
inherit=1767
invmodel=50621
placeholderid=23942
name="Crystal of Amlodd"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Amlodd (blue) (placeholder)
[[item]]
id=23942
inherit=1767
invmodel=50621
name="null"
placeholderid=23941
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of Calen (dark green)
[[item]]
id=32176
inherit=1767
invmodel=50622
placeholderid=32177
name="Crystal of Calen"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of Calen (dark green) (placeholder)
[[item]]
id=32177
inherit=1767
invmodel=50622
name="null"
placeholderid=32176
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0

# Crystal of zenyte (orange)
[[item]]
id=32178
inherit=1767
invmodel=50623
placeholderid=32179
name="Crystal of Pharaoh"
grandexchange=false
notedid=-1
op5="Drop"
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0
price=250000

# Crystal of zenyte (orange) (placeholder)
[[item]]
id=32179
inherit=1767
invmodel=50623
name="null"
placeholderid=32178
placeholdertemplate=14401
zoom=1104
modelroll=36
modelpitch=252
modelyaw=0
offsetx=0
offsety=0