[[npc]]
id=14037
inherit=7700
name="JalRek-Jad"
op1="Talk-to"
op2="Metamorphosis"
op3="Pick-up"
familiar=true
size=1
resizex=25
resizey=25
combatlevel=0
chatmodels=[29320]

[[npc]]
inherit=5893
op1="Talk-to"
op2="Metamorphosis"
op3="Pick-up"