[[npc]]
id=16000
inherit=453
name="Crawling Hand"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16001
inherit=483
name="Cave Bug"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16002
inherit=406
name="Cave Crawler"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16003
inherit=414
name="Banshee"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=60
resizey=60
combatlevel=0

[[npc]]
id=16004
inherit=480
name="Cave Slime"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=60
resizey=60
combatlevel=0

[[npc]]
id=16005
inherit=421
name="Rockslug"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16006
inherit=461
name="Desert Lzard"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16007
inherit=419
name="Cockatrice"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16008
inherit=433
name="Pyrefiend"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16009
inherit=2592
name="Mogre"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16010
inherit=464
name="Harpie"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16011
inherit=469
name="Killerwatts"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16012
inherit=1
name="Molanisk"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16013
inherit=417
name="Basilisk"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0



[[npc]]
id=16015
inherit=6473
name="Terror dog"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16016
inherit=626
name="Fever spiders"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=30
resizey=30
combatlevel=0

[[npc]]
id=16017
inherit=8614
name="Sulphur Lizards"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16018
inherit=443
name="Infernal Mage"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=60
resizey=60
combatlevel=0

[[npc]]
id=16019
inherit=4501
name="Brine rat"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16020
inherit=484
name="Bloodveld"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16021
inherit=437
name="Jelly"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16022
inherit=426
name="Turoth"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16023
inherit=473
name="Zygomite"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=75
resizey=75
combatlevel=0

[[npc]]
id=16024
inherit=3209
name="Cave horror"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16025
inherit=2
name="Aberrant spectre"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16026
inherit=423
name="Dust Devil"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16027
inherit=7793
name="Taloned Wyvern"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16028
inherit=7794
name="Spitting Wyvern"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16029
inherit=410
name="Kurask"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0


[[npc]]
id=16032
inherit=465
name="Skeletal Wyvern"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0


[[npc]]
id=16033
inherit=412
name="Gargoyle"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16034
inherit=8092
name="Brutal Black Dragon"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16035
inherit=8
name="Nechryael"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16036
inherit=7795
name="Ancient Wyvern"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0


[[npc]]
id=16037
inherit=8612
name="Drake"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16038
inherit=4005
name="Dark Beast"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

[[npc]]
id=16039
inherit=6593
name="Lava Dragon"
op1="Talk-to"
op2="Pick-up"
familiar=true
size=1
resizex=50
resizey=50
combatlevel=0

# Spooky Lava Dragon Inventory
[[item]]
id=27500
inherit=1561
name="Lava Dragon"
placeholderid=27501
invmodel=28512
primarymalemodel=-1
primaryfemalemodel=-1
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
zoom=1574
modelroll=440
modelpitch=320
modelyaw=82
offsetx=18
offsety=-276

#Spooky Lava Dragon Placeholder
[[item]]
id=27501
inherit=4034
name="null"
placeholdertemplate=14401
placeholderid=27500


