id=1713
name="easter_noticeboard"

[[component]]
inherit="220:0"

[[component]]
inherit="220:1"
color="000000"
font=497

[[component]]
inherit="220:2"
color="000000"
font=497

[[component]]
inherit="220:3"
color="000000"
font=497

[[component]]
inherit="220:4"
color="000000"
font=497

[[component]]
inherit="220:5"
color="000000"
font=497

[[component]]
inherit="220:6"
color="000000"
font=497

[[component]]
inherit="220:7"
color="000000"
font=497

[[component]]
inherit="220:8"
color="000000"
font=497

[[component]]
inherit="220:9"
color="000000"
font=497

[[component]]
inherit="220:10"
color="000000"
font=497

[[component]]
inherit="220:11"
color="000000"
font=497

[[component]]
inherit="220:12"
color="000000"
font=497

[[component]]
inherit="220:13"
color="000000"
font=497

[[component]]
inherit="220:14"
color="000000"
font=497

[[component]]
inherit="220:15"
color="000000"
font=497

# Close button
[[component]]
inherit="220:16"

[[component]]
inherit="220:17"

[[component]]
inherit="220:18"
