id=1701
name="game_noticeboard"

# Universe
[[component]]
name="universe"
type="layer"
width=190
height=261
onload=[31, "component:scroll_bar", "component:scroll_layer", 792, 789, 790, 791, 773, 788]

# Main container
[[component]]
name="main_container"
type="layer"
layer="universe"
x=3
y=26
width=184
height=229

# Layout
[[component]]
name="layout"
type="layer"
layer="universe"
x=3
y=26
width=184
height=229
onload=[712, "component:self", 0]

# Background
[[component]]
type="rectangle"
layer="main_container"
widthmode=1
heightmode=1
color="170801"
opacity=166
filled=true

# Title header
[[component]]
type="text"
layer="universe"
text="Game Noticeboard"
font=496
xallignment=1
yalllignment=1
y=4
widthmode=1
height=18

# Scroll layer
[[component]]
name="scroll_layer"
type="layer"
layer="main_container"
x=5
y=5
width=157
height=12
heightmode=1
scrollheight=522

# Scroll bar
[[component]]
name="scroll_bar"
type="layer"
layer="main_container"
x=162
y=5
width=16
height=218

[[component]]
type="text"
layer="scroll_layer"
text="Server Information"
font=496
x=2
y=2
widthmode=1
height=10

# Players online
[[component]]
name="players_online"
type="text"
layer="scroll_layer"
text="Players online: 0"
font=494
x=2
y=22
widthmode=1
height=10
onload=[3504, "component:self", "component:tooltip"]
onvartransmit=[3504, "component:self", "component:tooltip"]
vartransmittriggers=[3502, 3508]

# Staff online
[[component]]
name="staff_online"
type="text"
layer="scroll_layer"
text="Staff online: 0"
font=494
op1="<col=ff981f>View</col>"
opbase="Online staff"
clickmask=2
x=2
y=38
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]
onvartransmit=[3502, "component:players_online", "component:self", "component:players_in_wilderness"]
vartransmittriggers=[3502, 3508]

# Players in wilderness
[[component]]
name="players_in_wilderness"
type="text"
layer="scroll_layer"
text="Players in Wilderness: 0"
font=494
x=2
y=54
widthmode=1
height=10
onload=[3502, "component:players_online", "component:staff_online", "component:self"]
onvartransmit=[3502, "component:players_online", "component:staff_online", "component:self"]
vartransmittriggers=[3502, 3503, 3509]

# Up-time
[[component]]
type="text"
layer="scroll_layer"
text="Up-time:"
font=494
x=2
y=70
widthmode=1
height=10
onload=[3500, "component:self", "component:time_played", "component:personal_bonus_xp", "component:bonus_xp", "component:cox_boost", 1]

# Time
[[component]]
type="text"
layer="scroll_layer"
text="Time:"
font=494
x=2
y=86
widthmode=1
height=10

[[component]]
type="text"
layer="scroll_layer"
text="Player Information"
font=496
x=2
y=116
widthmode=1
height=10

# DonationPoints
[[component]]
type="text"
layer="scroll_layer"
text="Donation points"
font=494
color="ff0000"
opbase="Donation points"
x=2
y=136
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff0000"]
onvartransmit=[3503, "component:self"]
vartransmittriggers=[3505]

# XP mode
[[component]]
type="text"
layer="scroll_layer"
text="XP:"
font=494
x=2
y=152
widthmode=1
height=10

# Time played
[[component]]
name="time_played"
type="text"
layer="scroll_layer"
text="Time played:"
font=494
x=2
y=168
widthmode=1
height=10

# Registered on
[[component]]
type="text"
layer="scroll_layer"
text="Registered on:"
font=494
x=2
y=184
widthmode=1
height=10

# Privilege
[[component]]
type="text"
layer="scroll_layer"
text="Privilege:"
font=494
x=2
y=200
widthmode=1
height=10

# Game mode
[[component]]
type="text"
layer="scroll_layer"
text="Mode:"
font=494
x=2
y=216
widthmode=1
height=10

# Member rank
[[component]]
type="text"
layer="scroll_layer"
text="Member:"
font=494
x=2
y=232
widthmode=1
height=10

# Loyalty points
[[component]]
type="text"
layer="scroll_layer"
text="pharaoh points:"
font=494
x=2
y=248
widthmode=1
height=10

# Total donated
[[component]]
type="text"
layer="scroll_layer"
text="Total donated:"
font=494
x=2
y=264
widthmode=1
height=10

# Vote credits
[[component]]
type="text"
layer="scroll_layer"
text="Vote credits:"
font=494
x=2
y=280
widthmode=1
height=10

# Vote credits
[[component]]
type="text"
layer="scroll_layer"
text="Donation points:"
font=494
x=2
y=280
widthmode=1
height=10


# Game settings icon
[[component]]
type="graphic"
layer="scroll_layer"
sprite=10006
x=2
y=295
width=13
height=13

# Game settings
[[component]]
type="text"
layer="scroll_layer"
text="Game Settings"
opbase="Game Settings"
op1="<col=ff981f>Open</col>"
clickmask=2
font=494
x=17
y=296
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]

# Drop viewer icon
[[component]]
type="graphic"
layer="scroll_layer"
sprite=1113
y=309
width=18
height=16

# Drop Viewer
[[component]]
type="text"
layer="scroll_layer"
text="Drop Viewer"
opbase="Drop Viewer"
op1="<col=ff981f>Open</col>"
clickmask=2
font=494
x=17
y=312
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]

# Daily challenges icon
[[component]]
type="graphic"
layer="scroll_layer"
sprite=10001
x=2
y=327
width=13
height=13

# Daily Challenges
[[component]]
type="text"
layer="scroll_layer"
text="Daily Challenges"
opbase="Daily Challenges"
op1="<col=ff981f>Open</col>"
clickmask=2
font=494
x=17
y=328
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]

[[component]]
type="text"
layer="scroll_layer"
text="Boosts"
font=496
x=2
y=358
widthmode=1
height=10

# Bonus XP
[[component]]
name="personal_bonus_xp"
type="text"
layer="scroll_layer"
text="Private BXP:"
tooltip="Private 50% Bonus experience boost<br>Does not stack with the global boost."
font=494
x=2
y=394
widthmode=1
height=10





#TODO: Adding space here

# Global Bonus XP
[[component]]
name="bonus_xp"
type="text"
layer="scroll_layer"
text="Global BXP:"
tooltip="Global 50% Bonus experience boost<br>Does not stack with the private boost."
font=494
x=2
y=378
widthmode=1
height=10

















# CoX Boost
[[component]]
name="cox_boost"
type="text"
layer="scroll_layer"
text="CoX Boost:"
tooltip="25% Extra points in Chambers of Xeric"
font=494
x=2
y=410
widthmode=1
height=10

[[component]]
type="text"
layer="scroll_layer"
text="Useful Links"
font=496
x=2
y=440
widthmode=1
height=10

# Website icon
[[component]]
type="graphic"
layer="scroll_layer"
sprite=10002
x=2
y=457
width=13
height=13

# Website
[[component]]
type="text"
layer="scroll_layer"
text="Website"
opbase="Website"
op1="<col=ff981f>Visit</col>"
clickmask=2
font=494
x=17
y=459
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]

# Forums icon
[[component]]
type="graphic"
layer="scroll_layer"
sprite=10003
x=2
y=475
width=13
height=13

# Forums
[[component]]
type="text"
layer="scroll_layer"
text="Forums"
opbase="Forums"
op1="<col=ff981f>Visit</col>"
clickmask=2
font=494
x=17
y=475
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]

# Discord icon
[[component]]
type="graphic"
layer="scroll_layer"
sprite=10004
x=2
y=489
width=13
height=13

# Discord
[[component]]
type="text"
layer="scroll_layer"
text="Discord"
opbase="Discord"
op1="<col=ff981f>Visit</col>"
clickmask=2
font=494
x=17
y=491
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]

# Store icon
[[component]]
type="graphic"
layer="scroll_layer"
sprite=10005
x=2
y=505
width=13
height=13

# Store
[[component]]
type="text"
layer="scroll_layer"
text="Store"
opbase="Store"
op1="<col=ff981f>Visit</col>"
clickmask=2
font=494
x=17
y=507
widthmode=1
height=10
onmouseover=[45, "component:self", "color:ffffff"]
onmouseleave=[45, "component:self", "color:ff981f"]

# Tooltip
[[component]]
name="tooltip"
type="layer"
layer="universe"
width=1
height=1



