[[enum]]
inherit=3077

[enum.values]
13342=3194

[[enum]]
inherit=3194

[enum.values]
0=13342

[[enum]]
inherit=3292

[enum.values]
38=13342

[[enum]]
inherit=3302

[enum.values]
13342="Max cape"

[[enum]]
inherit=3304

[enum.values]
13342=3306