# Slayer rewards
[[enum]]
inherit=840
default=-1

[enum.values]
clear=true
0=11866
1=11875
2=4160
3=13226
4=12791
5=10551
6=12863
7=10887
8=11738
9=4081
10=13379
11=13381
12=13380
13=13377
14=13378
15=6714
16=10581
17=2952
18=22398
19=24699
20=10587
21=24266
22=6746
23=21817
24=989
25=2
26=25781
27=11230
28=11681
29=13116
30=50750

# Slayer reward quantities
[[enum]]
inherit=841
default=-1

[enum.values]
clear=true
4160=250
11875=250
11681=1
213116=1

# Slayer reward costs
[[enum]]
inherit=842
default=-1

[enum.values]
clear=true
4160=35
11866=75
50750=100
13226=750
11875=35
12791=750
10551=400
12863=300
10887=200
11738=10
4081=40
13379=40
13381=40
13380=40
13377=40
13378=40
6714=200
10581=150
2952=100
22398=150
24699=300
10587=40
24266=50
6746=400
21817=100
989=10
2=100
25781=300
11230=100
11681=50
13116=250



# Slayer reward information
[[enum]]
inherit=843
default="You may exchange your points for this item."

[enum.values]
clear=true
4160="Arrows that can pierce the hides of creatures such as Turoth and Kurasks. Levels 55 Slayer and 50 Ranged required, and a magic bow or better."
11866="A wieldable ring that can check your task progress. It has 8 charges for teleporting to useful Slayer sites."
13226="The herb sack has the ability to store up to 30 of each major grimy herb. Requires 58 Herblore to use."
11875="Crossbow bolts that can pierce the hides of creatures such as Turoth and Kurasks. Levels 55 Slayer and 61 Ranged required, and a runite crossbow or better."
12791="The rune pouch has the ability to store up to 16,000 runes of 3 types."
10551="A torso worn by penance fighters. Requires level 40 Defence."
12863="A powerful ranging device that fires metal balls."
10887="An anchor used by the Barrelchest. Requires level 60 Attack & 40 Strength."
11738="A herb box containing an assortment of random herbs, giving ten herbs per box."
4081="An amulet which increases wthe wearer's strength and accuracy by 15% when fighting the undead."
13379="A helmet from the Shayzien guards, used for protection against lizardmen."
13381="A platebody from the Shayzien guards, used for protection against lizardmen."
13380="Some greaves from the Shayzien guards, used for protection against lizardmen."
13377="Some gloves from the Shayzien guards, used for protection against lizardmen."
13378="Some boots from the Shayzien guards, used for protection against lizardmen."
6714="A shining paragon of wrenchly virtue."
2952="A silver dagger that can prevent werewolves from changing form."
22398="Used to fight Vampyres."
24699="Super effective against Vampyres."
10581="A sharp mystical dagger that can penetrate through Kalphite chitin."
10587="Tarn Razorlor's diary, used for enchanting salve amulets."
24266="A recreation of V's mighty shield."
6746="The magical sword 'Silverlight', enhanced with the blood of Agrith-Naar."
21817="The bracelet is dull and powerless."
989="A mysterious key for a mysterious chest."
2="250 xAmmo for the Dwarf Cannon."
11230=" 250 x A deadly throwing dart with a dragon tip."
25781="Scatters ashes."
11681="(i) Ur Desired Item with this Scroll."
13116="Bury's your bones."
50750="250x Spawns Nex to fight."
