# CRYSTAL BOWL ARMOUR
[[object]]
inherit=17239
id=50006
name="Singing bowl (armour)"



# Larran Chest OPEN
[[object]]
inherit=17239
id=50007
name="Singing bowl (weapons)"


# Larran Chest OPEN
[[object]]
inherit=17239
id=50008
name="Singing bowl (tools)"


