# Beginner scroll box
[[item]]
id=2803
inherit=2803
name="Scroll box (beginner)"
stackable=1
grandexchange=false
members=true
op1="Open"
op2=""
op5="Drop"
price=50
shiftclickindex=-2
zoom=770
offsetx=1
offsety=-6
modelpitch=236
modelroll=1697
modelyaw=0
invmodel=53002
placeholderid=30218
placeholdertemplate=-1

#Placeholder
[[item]]
id=30218
inherit=14577
placeholdertemplate=14401
placeholderid=2803

# Easy scroll box
[[item]]
id=2805
inherit=2805
name="Scroll box (easy)"
stackable=1
grandexchange=false
members=true
op1="Open"
op2=""
op5="Drop"
price=50
shiftclickindex=-2
zoom=770
offsetx=1
offsety=-6
modelpitch=236
modelroll=1697
modelyaw=0
invmodel=53003
placeholderid=30219
placeholdertemplate=-1

#Placeholder
[[item]]
id=30219
inherit=14577
placeholdertemplate=14401
placeholderid=2805

# Medium scroll box
[[item]]
id=2807
inherit=2807
name="Scroll box (medium)"
stackable=1
grandexchange=false
members=true
op1="Open"
op2=""
op5="Drop"
price=50
shiftclickindex=-2
zoom=770
offsetx=1
offsety=-6
modelpitch=236
modelroll=1697
modelyaw=0
invmodel=53005
placeholderid=30220
placeholdertemplate=-1

#Placeholder
[[item]]
id=30220
inherit=14577
placeholdertemplate=14401
placeholderid=2807

# Hard scroll box
[[item]]
id=2809
inherit=2809
name="Scroll box (hard)"
stackable=1
grandexchange=false
members=true
op1="Open"
op2=""
op5="Drop"
price=50
shiftclickindex=-2
zoom=770
offsetx=1
offsety=-6
modelpitch=236
modelroll=1697
modelyaw=0
invmodel=53000
placeholderid=30221
placeholdertemplate=-1

#Placeholder
[[item]]
id=30221
inherit=14577
placeholdertemplate=14401
placeholderid=2809

# Elite scroll box
[[item]]
id=2811
inherit=2811
name="Scroll box (elite)"
stackable=1
grandexchange=false
members=true
op1="Open"
op2=""
op5="Drop"
price=50
shiftclickindex=-2
zoom=770
offsetx=1
offsety=-6
modelpitch=236
modelroll=1697
modelyaw=0
invmodel=53004
placeholderid=30222
placeholdertemplate=-1

#Placeholder
[[item]]
id=30222
inherit=14577
placeholdertemplate=14401
placeholderid=2811

# Master scroll box
[[item]]
id=2813
inherit=2813
name="Scroll box (master)"
stackable=1
grandexchange=false
members=true
op1="Open"
op2=""
op5="Drop"
price=50
shiftclickindex=-2
zoom=770
offsetx=1
offsety=-6
modelpitch=236
modelroll=1697
modelyaw=0
invmodel=53001
placeholderid=30223
placeholdertemplate=-1

#Placeholder
[[item]]
id=30223
inherit=14577
placeholdertemplate=14401
placeholderid=2813