# Ash sanctifier
[[item]]
id=32326
invmodel=50816
name="Ash sanctifier"
zoom=1545
modelpitch=104
modelroll=67
offsetx=1
offsety=-9
stackable=0
members=true
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","Check","Activity","Uncharge","Destroy"]
originalcolours=[]
replacementcolours=[]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=10
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32327
placeholdertemplate=-1
parameters={ clear=true }


# Ash sanctifier (Placeholder)
[[item]]
id=32327
invmodel=0
name="null"
zoom=2000
modelpitch=0
modelroll=0
offsetx=0
offsety=0
stackable=0
members=false
primarymalemodel=-1
secondarymalemodel=-1
primaryfemalemodel=-1
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","","","","Drop"]
originalcolours=[]
replacementcolours=[]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=32326
placeholdertemplate=14401
parameters={ clear=true }


