# Holy sanguinesti staff (uncharged)
[[item]]
id=32316
invmodel=50766
name="Holy sanguinesti staff (uncharged)"
zoom=2258
modelpitch=552
modelroll=1558
offsetx=-5
offsety=3
stackable=0
members=true
primarymalemodel=50767
secondarymalemodel=-1
primaryfemalemodel=50768
secondaryfemalemodel=-1
groundops=["","","Take","",""]
ops=["","Wield","Charge","","Dismantle"]
originalcolours=[]
replacementcolours=[]
originaltextureids=[]
replacementtextureids=[]
shiftclickindex=-2
grandexchange=false
tertiarymalemodel=-1
tertiaryfemalemodel=-1
primarymaleheadmodelid=-1
primaryfemaleheadmodelid=-1
secondarymaleheadmodelid=-1
secondaryfemaleheadmodelid=-1
modelyaw=0
notedid=-1
notedtemplate=-1
stackids=[]
stackamounts=[]
resizex=128
resizey=128
resizez=128
ambient=0
contrast=0
teamid=0
bindid=-1
bindtemplateid=-1
placeholderid=-1
placeholdertemplate=-1
parameters={ clear=true }


