# Stardust #1
[[item]]
id=30546
inherit=23083
name="Stardust"
placeholderid=50551
invmodel=50298
price=1
primarymalemodel=-1
primaryfemalemodel=-1
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
op2=""
stackids=[30547,30548,30549,30550]
stackamounts=[25,75,125,175]
grandexchange=false
notedid=-1

# Stardust #25
[[item]]
id=30547
inherit=23083
name="Stardust"
placeholderid=50551
invmodel=50299
price=1
primarymalemodel=-1
primaryfemalemodel=-1
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
op2=""
grandexchange=false
notedid=-1

# Stardust #75
[[item]]
id=30548
inherit=23083
name="Stardust"
placeholderid=50551
invmodel=50300
price=1
primarymalemodel=-1
primaryfemalemodel=-1
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
op2=""
grandexchange=false
notedid=-1

# Stardust #125
[[item]]
id=30549
inherit=23083
name="Stardust"
placeholderid=50551
invmodel=50300
price=1
primarymalemodel=-1
primaryfemalemodel=-1
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
op2=""
grandexchange=false
notedid=-1

# Stardust #175
[[item]]
id=30550
inherit=23083
name="Stardust"
placeholderid=50551
invmodel=50300
price=1
primarymalemodel=-1
primaryfemalemodel=-1
secondarymalemodel=-1
secondaryfemalemodel=-1
tertiarymalemodel=-1
tertiaryfemalemodel=-1
op2=""
grandexchange=false
notedid=-1

# Stardust Placeholder
[[item]]
id=50551
inherit=21026
name="null"
placeholdertemplate=14401
placeholderid=30546
invmodel=50298
notedid=-1