# Barrows Teleport Scroll
[[item]]
inherit=12100
name="Barrows teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Godwars Teleport Scroll
[[item]]
inherit=12101
name="Godwars teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""


# Zulrah Teleport Scroll
[[item]]
inherit=12102
name="Zulrah teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Kraken Teleport Scroll
[[item]]
inherit=12103
name="Kraken teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Cerberus Teleport Scroll
[[item]]
inherit=12104
name="Cerberus teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Dagannoth Kings Teleport Scroll
[[item]]
inherit=12105
name="Dagannoth kings teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Callisto Teleport Scoll
[[item]]
inherit=12106
name="Callisto teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Veneantis Teleport Scoll
[[item]]
inherit=12107
name="Veneantis teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Vetion Teleport Scoll
[[item]]
inherit=12108
name="Vetion teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# King Black Dragon Teleport Scoll
[[item]]
inherit=12109
name="King Black Dragon teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Scorpia Teleport Scoll
[[item]]
inherit=12110
name="Scorpia teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Choas Hut
[[item]]
id=32305
inherit=12110
name="Chaos altar teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Resource Area
[[item]]
id=32306
inherit=12110
name="Wilderness resource area teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=true
op2=""

# Inferno
[[item]]
id=32238
inherit=12110
name="Inferno teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=false
op2=""

# Nex Teleport Scroll
[[item]]
inherit=12111
name="Nex teleport scroll"
invmodel=32770
originalcolours=[5563]
replacementcolours=[-26433]
grandexchange=false
op2=""
